config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get  'users/new',     to: "users#new",           as: "new_user"
  post 'users',         to: "users#create",        as: "users"

  get   'sessions/new', to: "sessions#new",    as: "new_session"
  post  'sessions',     to: "sessions#create", as: "sessions"
  delete'sessions',     to: "sessions#destroy"

  get   'goals',        to: "goals#index",     as: "goals"
  post 'goals',         to: "goals#create"
  get 'goals/new',      to: "goals#new",       as: "new_goal"
  get 'goals/:goal_id', to: "goals#show",      as: "goal"

  post 'requests',      to: "requests#create",    as: "requests"

  post 'participations',      to: "participations#create",    as: "participations"

  get '/api/goals',  to: 'api/goals#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :goals
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :admin, class_name: "User"
  belongs_to :category
  has_many :requests
  has_many :participations
  has_many :users, through: :participations
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :goal
  belongs_to :user
  belongs_to :status

end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :requests

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :goals, foreign_key: :admin_id
  has_many :requests
  has_many :participations
end

app/controllers/api/goals_controller.rb
class Api::GoalsController < ApplicationController
  def index
    render json: Goal.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  helper_method :current_user

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all.includes(:category, :admin)
  end

  def new
    @goal = Goal.new
    @categories = Category.all
  end

  def create
    goal = current_user.goals.create(goal_params)
    current_user.participations.create(goal_id: goal.id)
    redirect_to goals_path
  end

  def show
    @goal = Goal.find_by_id(params[:goal_id])
    @admin = @goal.admin
    @category = @goal.category
    session[:goal_id] = @goal.id

    @requests = @goal.requests.where(status: 1)
    @users = @goal.users
  end

private

  def goal_params
    params.require(:goal).permit(:title, :description, :category_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end


end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    Participation.create(user_id: params[:request_user_id].to_i, goal_id: session[:goal_id])
    Request.find_by_id(params[:request_id].to_i).update(status_id: 2)
    redirect_to :back
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
    goal = Goal.find_by_id(session[:goal_id])
    participants = goal.users
    requester_ids = goal.requests.pluck(:user_id)

    if !participants.include?(current_user) && !requester_ids.include?(current_user.id)
      Request.create(goal_id: session[:goal_id], user_id: current_user.id, status_id: 1)
    end
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params["email"]).try(:authenticate, params["password"])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to new_session_path
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.create :user_name => params["user"]["user_name"], :email => params["user"]["email"], :password => params["user"]["password"]
    session[:user_id] = user.id
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/index.erb
<h1> Goals Index </h1>

<%= link_to "Add goal", new_goal_path %>

<% @goals.each do |goal| %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Category: <%=  goal.category.title %> | Title: <%= link_to goal.title, goal_path(goal)%> | Author: <%= goal.admin.user_name %></h3>
    </div>
    <div class="panel-body">
      <div class="well">
        <%= goal.description %>
      </div>
    </div>
  </div>

<% end %>

app/views/goals/new.erb
<%= form_for @goal do |f| %>
  <%= f.label :category_id %>
  <%= f.collection_select :category_id ,@categories,:id,:title %>
  <%#= f.text_field :category_id %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/goals/show.erb
<h1><%=@goal.title%></h1>
<h1><%=@admin.user_name%></h1>
<h1><%=@goal.description%></h1>
<h1><%=@category.title%></h1>
<%= link_to "join this goal", requests_path, method: :post %>

<h2>Participants</h2>
<% @users.each do |user| %>
  <p>
    <%= user.user_name %>
  </p>
<% end %>



<h2>Pending Requests</h2>

<% @requests.each do |request| %>
  <p>
    Name: <%= request.user.user_name %>
    Status: <%= request.status.title %>
    <%= form_tag participations_path do  %>
      <%= hidden_field_tag(:request_id, request.id) %>
      <%= hidden_field_tag(:request_user_id, request.user_id) %>
      <%= submit_tag "Accept" %>
    <% end %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abildy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Abildy</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Goals", goals_path %></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li>logged in as: <%= current_user.user_name %> </li>
          <li><%= link_to "Sign Out", sessions_path, method: :delete%></li>
        <%else%>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_session_path %></li>
        <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/welcome.erb
<h1></h1>

<div class="jumbotron">
  <h1>Welcome to Abildy!</h1>
  <p>Find an accountability buddy and acheive your goals together</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Join Now!</a></p>
</div>

app/views/users/new.erb
<%= form_for @user do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>